Repository CADS-Dry-INC-Sons/inventory-app, pull requests merged in 2023-11, with the labels that each got.

#30 Installed Bootstrap!
  package-lock.json
  package.json
  public/index.html
  public/react/components/Form.js
Labels: enhancement, Frontend

#37 installed express-validator and added server-side validation for POST…
  package-lock.json
  package.json
  server/routes/items.js
Labels: enhancement, Backend

#38 Add Messages and Renamed Form to Add Form
  public/react/components/AddForm.js
  public/react/components/App.js
  public/react/components/EditForm.js
  public/react/components/Item.js
  public/react/components/ItemShow.js
  public/react/components/ItemsList.js
Labels: bug, enhancement, Frontend

#40 LAST BIG PR
  public/react/components/AddForm.js
  public/react/components/App.js
  public/react/components/EditForm.js
  public/react/components/Item.js
  public/react/components/ItemShow.js
  public/react/components/ItemsList.js
  server/routes/items.js
Labels: enhancement, Frontend
